import type { NextPage } from 'next';
import Head from 'next/head';
import HomeComponent from '../components/HomeComponent/HomeComponent';
import Navbar from '../components/Navbar/Navbar';

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <HomeComponent />
      </main>
    </div>
  );
};

export default Home;
